name: coleta_portel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  google_maps_flutter: ^2.12.2
  cupertino_icons: ^1.0.8
  cloud_firestore: ^4.15.8 
  geolocator: ^10.1.0
  google_fonts: ^6.2.1
  iconify_flutter: ^0.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/home.jpg